### ISSUE TITLE
Push rejected, failed to detect set buildpack

### ISSUE THREAD

**Issue by moravcik** [Lostmyname/heroku-post-build-clean-buildpack#1]
I have tried to setup your buildpack (using Heroku new support for multiple buildpacks https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) but my build failed with following error message:

```
-----> Fetching set buildpack https://github.com/Lostmyname/heroku-post-build-clean-buildpack... done
 !     Push rejected, failed to detect set buildpack https://github.com/Lostmyname/heroku-post-build-clean-buildpack
```

Any idea how to fix this problem?

**Comment by rvetere** [comment]
same problem here :-/
